<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Invitation;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class InvitationTest extends TestCase
{
    use RefreshDatabase;

    public Invitation $invitation;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->invitation = Factory::factoryForModel(Invitation::class)->create();
    }

    /** @test */
    public function it_errors_when_trying_to_view_an_invitation_that_doesnt_exist()
    {
        $this->get('/api/invitation/abc')->assertStatus(404);
    }

    /** @test */
    public function it_gets_an_invitations()
    {
        $this->get('/api/invitation/'.$this->invitation->id)
            ->assertStatus(200)
            ->assertJson($this->invitation->toArray());
    }
}
